### ISSUE TITLE
Indexing vertical text

### ISSUE THREAD

**Issue by DFMdG89** [WolfgangFahl/pdfindexer#6]
Awesome functionality you have built! After letting it loose on my own files, I found that pdfindexer does not find vertical text, correct? I hope I am wrong, as most of my search terms are vertically positioned in tables...

**Comment by DFMdG89** [comment]
Of course I can rotate the PDF itself, then it works fine for those search words. It just needs two passes. Still interested in your thoughts though.

**Comment by WolfgangFahl** [comment]
Thank you for posting this issue. I am personally also interested in this kind of functionality. Unfortunately the default text extracting process of the underlying pdfbox library does not support this (yet?). I'll keep this issue open as a reminder should an improvement be available.

**Comment by WolfgangFahl** [comment]
I did some experiments and was actually able to get the x/y position of pdf parts as extra information. I did not pursue this further and won't incorporate in this project. So I am closing the issue - unfortunately without fullfilling your needs/wishes!
